language: ruby
rvm:
- 2.1.0
sudo: false
cache: bundler
install:
- bundle install --deployment
script:
- echo "<< insert test here  >>"
after_success:
- bundle exec middleman build
deploy:
  provider: s3
  access_key_id:
    secure: IVR7+zYw5s4GbAgKxriMX0id4sXLoG4A2o1tYAofUzJkK3NMloMQwxE6QhSG3S/Ko9ICHDNLym3eoVlM6FiG1mJPLngfeSpIoO7Fjix2EgbRA5ZDG7dc4TEeQ8yRC1X0x+16m26hWr43McjnnZV6B8axEF2tCCAt0U32Pbg3Xix0secFa89Zx3c254CUzKPEIdyx7vVlmrupJ2Xa4j/d9ZXb4IzZ7qCkLMplSu3BOPwVkwL0ebaUFcVMQDGaXigYQPlDVQe00rbxwC54deQmO5ZetN4tpXPDYKAQi3N0X853TOAmiQFo5csYMDNca7K7ILXVRxtdGdf37Si+9a+YEk61nq7Cq7d+ONHYqk7cVueEFs2GaeyrWoWIshPLvwWoRdbQ4nzjE/TxejPgSTr3C1Flz4rzSRYIMaeZotRj55xIyNjaETB4DmKzY0ehvUrfjhhtYGi4w+jcDMkr8OulWggpLflhNt/emzNI0xiRFXF2x2ZaoAWvjVkYN/vBTMb8kBueQdyMF8Yls8kvwNDhkV8cVzECuuZl3Hm67ee6z1Su+xMzXroH7rEVGXSDxH0FUIYsl2I2J/j4LU4sbCaM9C7vhF0BA1V2J1SEcqkNfD35xPNJo3R1vr0B2m38I54ul3mu0K/wWb4HPwlQklWqTUfcvqoYE3+uvZz+Ofxclr0=
  secret_access_key:
    secure: pTl8SQNtWaHCCP3PlmCWB3G0NzZDMaVgCCTCeNMpmgiJpIPLMmStlM5lCCwgLZpOerTIkBK9+ZBqUml3TS1kmqLakXgsBAXfPrVtdEYAp37zAcZf+TEAMV9uYVOVyIc3mdUwcfITHGRx4QJgW02FxCt2HpZMUtRnp3U7vFdicRyA5Pdrwy194XFUPNnx3gXdwwMkb6Kf0j+RDxNROAplSHBgLYtDQmj7Cl1/pA5MDOLR5cSEHOwjmGG7caRKNkHyqE6W6+UF/VFGjJZ5k2iOR4b7WRVxb7r1i9iXmYHmQ+Nn6/PxAQ/UmgLsUh2pnptz4kVUFUYmr3jU9Az+lkLC5asvGza5kQyGjEows4QNHvMjbEDuw4jldSUnKN6fi6FvXgNWyjOb20S3JIBpXEweQr/HVKgUS8MGk8x8acFzpMz3+Rczhu6cfdJrqy//XdQxGeknaHKZw1lcCShd1iU2oG4+2QN4jBTN8g7jdtrRAA0Hs2G4ZkXUts9JVO3zID8m3bi6IuWY+xJsz0ORzY1D2hieFjqdvqRn2Gp5KVkedoOSgP1NlBWYZzKN9DOMgt3PcyH3seyHKxLbMiwpmtCcXwnmlhQ5pQzqI3PXZ0fdC1479NOYGKvUVN6hfn8cI2p6s0BvrNpZ/4oFciZFQM4xlAtMaUSYbPgn5RpUGtZPK/I=
  bucket: docs.plenar.io
  skip_cleanup: true
  local-dir: build
  acl: public_read
  on:
    branch: master
notifications:
  slack:
    secure: CxwiKC3leWb4zd6ofAHJlNBmjbWfMabJ6W8qW1AEhlLcsdLjdD4IJO1flHvd0IxY/2M1lSUD0XNGgXl6dF8Dd2ML/yUvXw0BwbU1TtZ1P2vuLAahczrgZ09lBR+sQJpEXYhDIrxJ8jL1LW7VQyGcseWpAfSUBna0YPEYu077LbgZka/eHvRsIUBOKoJLd5blfvLLVzVx51bEzDp1KN3XcWGSXNx/rdo8gf+MpPRF5k1W82TgGre1YM6A6itge2dbtShYzYf5CtyXQy6ppWwABHToynIxoZaI9chG8REnJyr8RwBUa4VoW12sqmg5XZkmE5oijREwtIX9e8gy1XAAS+8RhJmA3RLsVwhaQNtsdrx3Z9gdn7ZDln+F6WcaxqMQTpOOm40QMuO50yYpIO1A/cB+4zGe/T4cslPiQvLEAM43rPyMishQqq0WXR+xyAa7/Sktmjw8K7Ae50c9dy9qdbprUALlv6xf+1wksf1P47HEtY+ES6PxVWLFuGz3CdKdkoDHxrYX1KRqtvUoTac320fHOz9v/Wqn4DdocQLF94HMy7oyrzzAjFQGpXBVnWjwve6NNxdsfW3RpUYDsrBkx4DypIBONv3BnKJBOe480jn1s/svceGcW3LLy3kiJPJHR7bVV13F1+r+/qZmwZ3yfPVl6asd6CbA7S+JbaxO2HA=
